### ISSUE TITLE
Question for HMDB51-DVS dataset.

### ISSUE THREAD

**Issue by chenjq2** [jackd/events-tfds#2]
Thanks for your contribution! However, I found some mistakes in the HMDB51-DVS dataset. I downloaded this dataset in .aedat format, but your code only includes ways to load the .mat file, do you have any ideas about it? Is that the original author update its dataset?

**Comment by chenjq2** [comment]
Or do you have the '.mat' format dataset about hmdb51-dvs, maybe I can use that. THX

**Comment by jackd** [comment]
Hi @Gary-learner , looks like the .mat files have been removed from where they were on dropbox - that's annoying. It's been a while since I've written this and it's not something I have the time to address right now, but if you're looking for somewhere to start I'd look [here](https://github.com/jackd/events-tfds/blob/master/events_tfds/data_io/aedat.py#L81). From experience you might need to switch x / y coordinates after loading, I remember datasets never really agreed on the exact order...

Please let me know how you go. If it's not super straight forward I'll look into addressing it when I get the chance.

**Comment by chenjq2** [comment]
Thanks for your advice! Now I can handle the .aedat format file through your providing this file [https://github.com/jackd/events-tfds/blob/master/events_tfds/data_io/aedat.py](url), especially this code `def load_events(
    fp,
    filter_dvs=False,
    # bytes_skip=0,
    # bytes_trim=0,
    # times_first=False,
    **kwargs
):
    timestamp, addr = load_raw_events(
        fp,
        filter_dvs=filter_dvs,
        #   bytes_skip=bytes_skip,
        #   bytes_trim=bytes_trim,
        #   times_first=times_first
    )
    x, y, polarity = parse_raw_address(addr, **kwargs)
    return timestamp, x, y, polarity`. Thanks a lot!
